version: 0.2

phases: 

  install:
    runtime-versions:
      nodejs: 10
     

      
    pre_build:
      commands:
        - npm install
      finally:
        - echo Executing Pre Build Finally
    build:
      commands:
        - ng build --prod
