version: 0.2

phases: 
  install:
    runtime-versions:
      nodejs: 10
    commands:
      #Update Libs#
      - apt-get update
      # Headless Chrome
      - apt-get install -y fonts-liberation libasound2 libnspr4 libnss3 libx11-xcb1 xdg-utils libxssl
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - dpkg -i google-chrome*.deb
  pre_build:
    commands:
     - echo PATH
     - npm install
build:
   commands:
      - npm run build:ci 
      - npm run build:ci 
artifacts:
    files:
      - '**/*.html'
      - '**/*.js'
      - '**/*.css'
      - '**/*.ico'
    base-directory: 'dist/mvp-angular'

