version: 0.2

phases: 

  install:
    runtime-versions:
      nodejs: 10
     

      
    pre_build:
      commands:
        - npm install
      finally:
        - echo Executing Pre Build Finally
      build:
      commands:
        - ng build --prod
      artifacts:
        files:
          - '**/*.html'
          - '**/*.js'
          - '**/*.css'
          - '**/*.ico'
        discard-paths: yes
        base-directory: 'dist/mvp-angular'
